### ISSUE TITLE
25.0.13 | Stuck on loading when displaying Blob

### ISSUE THREAD

**Issue by WojciechRemberg** [intbot/ng2-pdfjs-viewer#286]
Hi,

I have the following problem with the lib.

In Angular 20 app, I'm showing viewer like so:

```
 <ng2-pdfjs-viewer
    [showDownload]="!isIonic && isOnline"
    [downloadFileName]="fileName"
    [showFullScreen]="false"
    [urlValidation]="false"
    [theme]="'light'"
    [pdfSrc]="blob"
 />
```

The property `blob` is of type `Blob`.

The viewer shows indefinite loading as if it crashed, console errors are:
`SECURITY ALERT: File URL has been modified!`
`Original: blob: <a url>`
`Current: blob: <same url with diff uuid>`
`Security Warning: Unauthorized file access detected. The file URL has been tampered with.`

I tried setting `[urlValidation]="false"` to no avail.
Also tried programmatically (`setUrlValidation(false)`) and got result `success: true`, then tried `refresh()` but it also did not help.

I'm downloading a `Blob` and trying to preview it using this library.

It worked without issue in the past (version 20.x.x), with the exception of not showing signatures (as in someone would sign a delivery document etc) added to pdf.

I should be able to disable this validation, right?

**Comment by codehippie1** [comment]
@WojciechRemberg Would you be able to create a minimally reproducible sample on Github or Stackblitz ?

**Comment by WojciechRemberg** [comment]
Thanks @codehippie1!

**Comment by codehippie1** [comment]
v25.0.14 is released.

**Comment by codehippie1** [comment]
I am not able to reproduce this. I also added a new test button to test blob changes. You may switch `[urlValidation]` on this new component (with id `externalBlobViewer`) to test this out

<img width="356" height="589" alt="Image" src="https://github.com/user-attachments/assets/b8f31da7-c966-466e-ab8e-44a4ce110aca" />

**Comment by codehippie1** [comment]
Are you using more than one viewer? Do you have a viewerId specified for the viewer? Get latest version (25.0.15) and try again. viewerId is needed when playing around with urlValidation = true. But in your case you are turning validation off, still...

**Comment by WojciechRemberg** [comment]
Also this happens when selecting theme `light`

<img width="677" height="54" alt="Image" src="https://github.com/user-attachments/assets/a835bd08-55c9-49ad-8cf1-0bfacb85ae4d" />

**Comment by WojciechRemberg** [comment]
I left out the info (maybe relevant?) that I display the viewer in angular material dialog.

---

I discovered that I can just pass `[showSpinner]="false"` and it "seems to be working" without issue (pdf is interactable).

I also passed `[diagnosticLogs]="true"` - here's what's shown:

`ActionQueueManager: Error executing action show-openfile: Error: Iframe not available`

And for each action (there's a lot of them) there's a separate equivalent error:

<img width="655" height="270" alt="Image" src="https://github.com/user-attachments/assets/b284a4df-bdf1-4aff-af9e-9c285d5d5aa7" />

**Comment by codehippie1** [comment]
Didn't get to this yet. Will take a look this week.

**Comment by codehippie1** [comment]
@WojciechRemberg Everything should be fixed now. I also added your sample into the repo for easy testing. Your scenario revealed a couple of issues, since you were loading the viewer after pdf file selection and destroying the iframe on dialog dismissal. Get v25.0.18 and test. 

Here is an updated stackblits (Forked from yours) -> https://stackblitz.com/edit/stackblitz-starters-h2myvozq

**Comment by WojciechRemberg** [comment]
Awesome, I'm going to test this now :)

**Comment by WojciechRemberg** [comment]
@codehippie1 

Loading and signatures now both work 😎

Light theme is still broken for me but it works in stackblitz so it's probably something on my end that overrides the styles.

<img width="1160" height="141" alt="Image" src="https://github.com/user-attachments/assets/24b739aa-d21b-422f-9f0e-4553a2898e31" />


Nevertheless, many thanks for enabling me :)

**Comment by WojciechRemberg** [comment]
@codehippie1 huh, I found that the `light` theme is broken because CSS variables like
```
    color: var(--ng2-text-color, var(--ng2-default-text)) !important;
```

Are not set and `--ng2-default-text` is chosen. Default is meant for dark theme so it looks broken.

I do have the angular.json glob config set up in my app. 

Am I missing some CSS asset?

EDIT: at least `--toolbar-icon-bg-color` is not set correctly

**Comment by codehippie1** [comment]
@WojciechRemberg Can you reproduce the theme issue on Stackblitz?

From your reply, it is hard to pinpoint the issue.

Also, if it work on stackblits, ideally all assets should be loading fine.

Fyi - The default theme is not light or dark, but system. The theme should adapt to the OS theme by default.

**Comment by WojciechRemberg** [comment]
@codehippie1 

I think the issue is, my mac/chrome is set to dark theme, while I was trying to force light theme just on the ng2-pdfjs-viewer.
If I set my mac's appearance to light, everything works.

On stackblitz it works because it doesn't seem to forward preferred color scheme.

It's probably some edge case with default when machine's theme is dark and ng2-pdfjs-viewer is set to light.

Anyway it doesn't block me :)

**Comment by codehippie1** [comment]
@WojciechRemberg Thanks for the clarification. Btw, I am on windows, not sure that has anything to do with it. If I can get a reproducible sample, I can get it fixed.

Unrelated - If you are working on a cool project and using my library, I have a showcase where you can display your work. Showcase is new, I set it up with this new version - https://angular-pdf-viewer-docs.vercel.app/showcase

**Comment by WojciechRemberg** [comment]
I will hold off on the showcase for now but many thanks for the fixes!

Closing the issue.
