### ISSUE TITLE
Default "theme" should be set to "auto" instead of "light"

### ISSUE THREAD

**Issue by lvalentieng** [intbot/ng2-pdfjs-viewer#288]
Currently, the default value for the `theme` parameter is set to `light`.

I suggest changing the default to `auto` so that the PDF viewer automatically adapts to the user's system theme (light or dark).

This would improve usability, especially for users with a dark system theme, as the PDF viewer may otherwise be displayed incorrectly.

Attached is a screenshot showing how the light theme appears when using a dark theme on Windows.

<img width="893" height="296" alt="Image" src="https://github.com/user-attachments/assets/8ff3e060-9bdc-4747-bc32-01927c33a52d" />

**Comment by codehippie1** [comment]
@lvalentieng I fixed this. Will be released with v25.0.15 (Most likely in an hour)

**Comment by RikeWen** [comment]
Yes, “auto” works fine now. However, there's still an issue when you select a different theme.

For example, if you select the “dark” theme in Windows and then the “light” theme in ng2-pdfjs-viewer, the same problem occurs: the icons are almost impossible to make out because the colors don't match.
