### ISSUE TITLE
Impossible to open pdf file with URL that contains parameters

### ISSUE THREAD

**Issue by aleshchenko** [intbot/ng2-pdfjs-viewer#8]
Viewer removes parameters from the pdf URL. Consider using URL like http://my.api/get?id=123&name=test

**Comment by codehippie1** [comment]
This is a valid request, I will update the component.

**Comment by javid-abd** [comment]
I'm tracking this issue. When can it be updated?

**Comment by codehippie1** [comment]
@aleshchenko @javid-abd This is being implemented

**Comment by codehippie1** [comment]
@aleshchenko @javid-abd None of the parameters should be removed now. If this issue still exists, give me a sample of all the options and url you are trying to use.

**Comment by codehippie1** [comment]
As there are no activity on this thread, assuming issue is resolved. Closing

**Comment by kimhonoridez** [comment]
Still got this issue.

My URL is something like:
http://localhost:88/api/get/pdf?pages=1,2,3,4

**Comment by aeslinger0** [comment]
This was still an issue for me as well when trying to download via a Presigned URL from an S3 bucket. Encoding the url before passing it to the viewer allowed me to work around it.

**Comment by tolgacesur** [comment]
This works for me

`this.pdfViewerAutoLoad.pdfSrc = encodeURIComponent(url);`

url is a presigned s3 bucket url

**Comment by mharrisn** [comment]
> This works for me
> 
> `this.pdfViewerAutoLoad.pdfSrc = encodeURIComponent(url);`
> 
> url is a presigned s3 bucket url

Just want to add a note - this does NOT work for all Presigned Urls. It's hit or miss. If the signature includes a +, this will still fail.
